baseURL = "https://www.adrianmoreno.info/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Adrián Moreno Peña · Web & Mobile Developer, all-around coder"
theme = "adritian-free-hugo-theme"


# Languages
#   en
#     weight: 1
#   es
#     weight: 2

[build]
  writeStats = true
  
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
 

# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "index.html#about"
  weight = 2

  [[menu.header]]
  name = "Experience"
  URL = "index.html#experience"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "💁‍♂️ About"
  URL = "index.html#about"
  weight = 2


  [[menu.footer]]
  name = "📚 Books"
  URL = "/books"
  weight = 3

  [[menu.footer]]
  name = "🎤 Public Speaking"
  URL = "/public-speaking"
  weight = 4

  [[menu.footer]]
  name = "📨 Contact"
  URL = "index.html#contact"
  weight = 5


[params]

  sections = ["showcase", "about", "education", "experience", "contact"]
  googleTagManagerID = "GTM-NVN2BJG" # Google Analytics works with Google Tag Manager
  homepageExperienceCount = 6

  [params.logo]
    text1 = "Adrián"
    text2 = "Moreno"

  [params.footer]
      copyright = "© Adrián Moreno Peña. <a href=\"https://github.com/zetxek/adrianmoreno.info\">Content</a> and <a href=\"https://github.com/zetxek/adritian-free-hugo-theme\">code available in GitHub</a>."

[taxonomies]
  book_author = "book_authors"
  book_category = "book_categories"
