baseURL: 'https://apourmand.ir/'
languageCode: en
DefaultContentLanguage: en
title: 'Amir Pourmand · ML Engineer'
theme: adritian-free-hugo-theme
build:
  writeStats: true
params:
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
  sections:
    - showcase
    #- about
    - education
    #- experience
    #- contact
  #googleTagManagerID: GTM-NVN2BJG
  homepageExperienceCount: 10
  logo:
    text1: Amir
    text2: Pourmand
  footer:
    copyright: >-
      © Amir Pourmand 
menu:
  header:
    - name: About
      URL: index.html#about
      weight: 2
    # - name: Experience
    #   URL: index.html#experience
    #   weight: 3
    # - name: Contact
    #   URL: '#contact'
    #   weight: 4
  footer:
    - name: "\U0001F481‍♂️ About"
      URL: index.html#about
      weight: 2
    #- name: "\U0001F4DA Books"
    #  URL: /books
    #  weight: 3
    # - name: "\U0001F3A4 Public Speaking"
    #   URL: /public-speaking
    #   weight: 4
    # - name: "\U0001F4E8 Contact"
    #   URL: index.html#contact
    #   weight: 5
# taxonomies:
#   book_author: book_authors
#   book_category: book_categories
